### Import Libraries

In [ ]:
import numpy as np
import pandas as pd
import warnings
warnings.filterwarnings("ignore")
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder, StandardScaler
from sklearn.tree import DecisionTreeClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import confusion_matrix, accuracy_score, classification_report

### Load Dataset


In [3]:
df = pd.read_csv(r'C:\Users\Ashish Mishra\OneDrive\Desktop\Machine Learning\Dataset.csv')
df.head(5)

Restaurant ID         Restaurant Name  Country Code              City  \
0        6317637        Le Petit Souffle           162       Makati City   
1        6304287        Izakaya Kikufuji           162       Makati City   
2        6300002  Heat - Edsa Shangri-La           162  Mandaluyong City   
3        6318506                    Ooma           162  Mandaluyong City   
4        6314302             Sambo Kojin           162  Mandaluyong City   

                                             Address  \
0  Third Floor, Century City Mall, Kalayaan Avenu...   
1  Little Tokyo, 2277 Chino Roces Avenue, Legaspi...   
2  Edsa Shangri-La, 1 Garden Way, Ortigas, Mandal...   
3  Third Floor, Mega Fashion Hall, SM Megamall, O...   
4  Third Floor, Mega Atrium, SM Megamall, Ortigas...   

                                     Locality  \
0   Century City Mall, Poblacion, Makati City   
1  Little Tokyo, Legaspi Village, Makati City   
2  Edsa Shangri-La, Ortigas, Mandaluyong City   
3      SM Megamall, Ortigas, Mandaluyong City   
4      SM Megamall, Ortigas, Mandaluyong City   

                                    Locality Verbose   Longitude   Latitude  \
0  Century City Mall, Poblacion, Makati City, Mak...  121.027535  14.565443   
1  Little Tokyo, Legaspi Village, Makati City, Ma...  121.014101  14.553708   
2  Edsa Shangri-La, Ortigas, Mandaluyong City, Ma...  121.056831  14.581404   
3  SM Megamall, Ortigas, Mandaluyong City, Mandal...  121.056475  14.585318   
4  SM Megamall, Ortigas, Mandaluyong City, Mandal...  121.057508  14.584450   

                           Cuisines  ...          Currency Has Table booking  \
0        French, Japanese, Desserts  ...  Botswana Pula(P)               Yes   
1                          Japanese  ...  Botswana Pula(P)               Yes   
2  Seafood, Asian, Filipino, Indian  ...  Botswana Pula(P)               Yes   
3                   Japanese, Sushi  ...  Botswana Pula(P)                No   
4                  Japanese, Korean  ...  Botswana Pula(P)               Yes   

  Has Online delivery Is delivering now Switch to order menu Price range  \
0                  No                No                   No           3   
1                  No                No                   No           3   
2                  No                No                   No           4   
3                  No                No                   No           4   
4                  No                No                   No           4   

   Aggregate rating  Rating color Rating text Votes  
0               4.8    Dark Green   Excellent   314  
1               4.5    Dark Green   Excellent   591  
2               4.4         Green   Very Good   270  
3               4.9    Dark Green   Excellent   365  
4               4.8    Dark Green   Excellent   229  

[5 rows x 21 columns]

### Dropping Unnecessary Columns

In [4]:
df.drop(['Restaurant ID', 'Country Code', 'City', 'Address', 'Locality', 
         'Locality Verbose', 'Longitude', 'Latitude', 'Currency', 
         'Has Table booking', 'Has Online delivery', 'Is delivering now', 
         'Switch to order menu', 'Price range', 'Aggregate rating', 
         'Rating color', 'Rating text', 'Votes'], axis=1, inplace=True)

In [5]:
df.head()

Restaurant Name                          Cuisines  \
0        Le Petit Souffle        French, Japanese, Desserts   
1        Izakaya Kikufuji                          Japanese   
2  Heat - Edsa Shangri-La  Seafood, Asian, Filipino, Indian   
3                    Ooma                   Japanese, Sushi   
4             Sambo Kojin                  Japanese, Korean   

   Average Cost for two  
0                  1100  
1                  1200  
2                  4000  
3                  1500  
4                  1500

In [6]:
print("Missing values in each column:")
print(df.isnull().sum())

df.dropna(inplace=True)
print("Shape after removing missing values:", df.shape)

Missing values in each column:
Restaurant Name         0
Cuisines                9
Average Cost for two    0
dtype: int64
Shape after removing missing values: (9542, 3)


### Encoding Categorical Variables

In [7]:
label_encoder = LabelEncoder()
df['Restaurant Name'] = label_encoder.fit_transform(df['Restaurant Name'])
df['Cuisines'] = label_encoder.fit_transform(df['Cuisines'])

df.head()

Restaurant Name  Cuisines  Average Cost for two
0             3742       920                  1100
1             3167      1111                  1200
2             2892      1671                  4000
3             4700      1126                  1500
4             5515      1122                  1500

### Splitting the Dataset

In [8]:
X = df[['Restaurant Name', 'Average Cost for two']]
Y = df['Cuisines']

scaler = StandardScaler()
X = scaler.fit_transform(X)

X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size=0.2, random_state=10)

### Decision Tree Classifier

In [9]:
model_DT = DecisionTreeClassifier(random_state=10, criterion="gini")
model_DT.fit(X_train, Y_train)

Y_pred_DT = model_DT.predict(X_test)

print("Confusion Matrix (Decision Tree):\n", confusion_matrix(Y_test, Y_pred_DT))
print("Classification Report (Decision Tree):\n", classification_report(Y_test, Y_pred_DT))
print("Accuracy (Decision Tree):", accuracy_score(Y_test, Y_pred_DT))

Confusion Matrix (Decision Tree):
 [[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 1 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
Classification Report (Decision Tree):
               precision    recall  f1-score   support

           0       0.00      0.00      0.00         2
           1       0.00      0.00      0.00         1
           6       0.25      0.14      0.18         7
           7       0.00      0.00      0.00         1
           8       0.00      0.00      0.00         1
           9       0.00      0.00      0.00         1
          11       0.00      0.00      0.00         1
          12       0.00      0.00      0.00         1
          13       0.00      0.00      0.00         1
          15       0.00      0.00      0.00         1
          16       1.00      1.00      1.00         2
          18       0.00      0.00      0.00         1
          20       0.00      0.00      0.00         1
          21       0.00      0.00      0.00     

c:\Users\Ashish Mishra\anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:1531: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
c:\Users\Ashish Mishra\anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:1531: UndefinedMetricWarning: Recall is ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
c:\Users\Ashish Mishra\anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:1531: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
c:\Users\Ashish Mishra\a

### Logistic Regression

In [10]:
classifier = LogisticRegression(multi_class="multinomial")
classifier.fit(X_train, Y_train)

Y_pred_LR = classifier.predict(X_test)

print("Confusion Matrix (Logistic Regression):\n", confusion_matrix(Y_test, Y_pred_LR))
print("Classification Report (Logistic Regression):\n", classification_report(Y_test, Y_pred_LR))
print("Accuracy (Logistic Regression):", accuracy_score(Y_test, Y_pred_LR))

c:\Users\Ashish Mishra\anaconda3\Lib\site-packages\sklearn\linear_model\_logistic.py:1247: FutureWarning: 'multi_class' was deprecated in version 1.5 and will be removed in 1.7. From then on, it will always use 'multinomial'. Leave it to its default value to avoid this warning.
  warnings.warn(


Confusion Matrix (Logistic Regression):
 [[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
Classification Report (Logistic Regression):
               precision    recall  f1-score   support

           0       0.00      0.00      0.00         2
           1       0.00      0.00      0.00         1
           6       0.00      0.00      0.00         7
           7       0.00      0.00      0.00         1
           8       0.00      0.00      0.00         1
           9       0.00      0.00      0.00         1
          11       0.00      0.00      0.00         1
          12       0.00      0.00      0.00         1
          13       0.00      0.00      0.00         1
          15       0.00      0.00      0.00         1
          16       0.00      0.00      0.00         2
          18       0.00      0.00      0.00         1
          20       0.00      0.00      0.00         1
          21       0.00      0.00   

c:\Users\Ashish Mishra\anaconda3\Lib\site-packages\sklearn\linear_model\_logistic.py:469: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
c:\Users\Ashish Mishra\anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:1531: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
c:\Users\Ashish Mishra\anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:1531: UndefinedMetricWarning: Recall is ill-defined and being se

### Observations:
1. **Decision Tree Classifier**:
    - Accuracy: 24.36%
    - Confusion Matrix and Classification Report are displayed above.
    - Handles complex data well but tends to overfit on training data.

2. **Logistic Regression**:
    - Accuracy: 10.58%
    - Confusion Matrix and Classification Report are displayed above.
    - Simpler model that works best for linearly separable data.

### Conclusion:
- **Decision Tree Classifier** performed significantly better compared to **Logistic Regression**, achieving a higher accuracy.
- However, the overall accuracy is low, indicating that additional preprocessing, feature engineering, or the use of more advanced models (e.g., Random Forest, Gradient Boosting) is necessary for better performance.